### ISSUE TITLE
Wrong stats

### ISSUE THREAD

**Issue by Apofenas** [FAForever/UnitDB#1]
Hello

The database has some problems showing weapon stats. All it shows is damage and its rof and thats wrong!

This causes database show false numbers for units with multiple projectiles, DamageOverTime, initial damage, DamageToShields and nuke weapons.

**Fire circle**
Your database shows 6 damage with 0.1 rof. = 0.6 DPS?
It's true stat should look like this:
Damage=20(initial damage)+6(DoT damage)*10(DoTPulses)*20(Muzzle Salvo Size)=1600
RateOfFire= 0.1
**DPS=160**

160 is much different from 0.6 right? All in all showing full fire circle is much more informative.

**Absolver**
This unit has its own special damage to shield. Even Spooky DB doesnt show it and shows 2.5 dps...
Meanwhile it has 1300 damage to shields and its DPS to shields is 650

**Nuke**
DB doesnt show nuke weapon stats. You know, NukeInnerRing, NukeOuterRing stats ect for Nuke launchers, UEF ACU, strat subs and sera BS.

**Similiar weapons**
Would be nice to hide similiar weapons as x2, x3 ect just like both old and Spooky DB do.

**Build rate and build power**
Possible to move them to some kind of different categories?

**Comment by louvenarde** [comment]
**Fire cycle and wrong stats**
The fire cycle displayed comes directly from the blueprint. Calculating the DPS is *not* as simple as multiplicating the damage with the RoF. There is currently no accurate enough DPS calculation algorithm for me to implement into the UnitDB, as I want everything displayed in the UnitDB to be perfectly accurate.
The UnitDB cannot possibly display a "wrong stat", since they are directly taken from the game files. However, some names can be misleading, or some information can be missing : in which case I encourage you to report it and suggest new names or new informations.
Keep in mind that every information must be taken from the blueprint and that _no information should ever be manually inputed in the unitDB_.

**Nuke**
You are right. I should display those. I will address this issue as soon as I can.

**Similar weapons**
I've thought about grouping similar weapons by stacks, but never made it. If you think this would be a good addition then I shall do it like so.

**Build rate and build power**
Why would you want to move them to different categories, and where would you want to move them exactly ?

**Comment by Apofenas** [comment]
**Fire circle**
In this case you could try to make data base to check all stats from fire circle: Initial damage, Damage, DoT pulses, Muzzle salvo size so it looks exactly as i described: (InitialDamage+Damage*DotPulses+*DamageToShields)*MuzzleSalvoSize. If the value isn't present - make it not appear just like damage radius.

You can use this formula to calculate the total amount of damage and put it instead of current "damage". This would also let you also calculate the DPS of the weapon and put it in the same line with TotalDamage and ROF.

**Similiar weapons**
If you do so check Seraphim destroyer: rear cannon has 50% less damage despite all other stats are similiar. 
**Btw you have to Overcharge weapons for sera SCU?**

**Build rate and build power**
That part of DB is kinda meh for somebody who uses it for first time. I actually got asked once what do those "clocks" mean.

**Comment by louvenarde** [comment]
Fixed in commit 0958bd39a5089b349f8c16d2bbf3af6a1189ba06 (v1.2.2)

- Added tooltips for Build rate / Build power and other economic values
- Grouped similar weapons with "x2" "x3" but only if they have the same damage, rateoffire, damage radius, and other stats in common
- Added nuke range/ring display
- Displayed DamageToShields, Dot stats, and other damage stats.

The update has been committed and will be pushed to the server as soon as possible. You should see the changes in the day or tomorrow.
